sudo: required
services:
  - docker

before_install: 
  - docker build -t salomonguttmann/docker-react_2 -f Dockerfile.dev .

script: 
  - docker run -e CI=true salomonguttmann/docker-react_2 npm run test   

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-eu-west-3-248749481552"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY" 






