#no org
language: python
python:
  - '3.8'

sudo: required
services:
  - docker

before_install: 
  - docker build -t salomonguttmann/docker-react_2 -f Dockerfile.dev .

script: 
  - docker run -e CI=true salomonguttmann/docker-react_2 npm run test
  

deploy:
  provider: gae
  keyfile: quick-filament-378505-457ba39e057d.json
  project: quick-filament-378505
  on:
    branch: master








