#Ist meine ersten Test für Travis CI
sudo: required
services:
  - docker

before_install: 
  - docker build -t SalomonGuttmann/docker-react_2 -f Dockerfile.dev .

script: 
  - docker run -e CI=true SalomonGuttmann/docker-react_2 npm run test   