
FROM node:16.3.0-alpine
RUN gem install nokogiri

#RUN addgroup app && adduser -S -G app app
#RUN mkdir /app && chown -R app:app /app
RUN mkdir /app && chown -R node:node /app
RUN chmod 777 /app -R
#USER app
USER node
WORKDIR /app


#COPY package.json .
COPY --chown=node:node package.json ./
RUN npm install 

#COPY . .
COPY --chown=node:node . .

CMD ["npm", "run", "start"]


